### PR TITLE
Swav checks

### PR DESCRIPTION
**Pull request by Atharva-Phatak**
## What does this PR do?

Quality checks for implementations of SWAV https://github.com/Lightning-AI/lightning-bolts/issues/839

**Couple of points I would like to highlight.**

* Right now bolts is focused on standard datasets like CIFAR10, etc but it will be very amazing if we can adapt SSL module for custom tasks.
* The SSL fine tuner is just a normal lightingModule we can remove it and let the user create one according to his/her needs. We will just provide the basic models and functionalities required for implementing SSL tasks.
 * These changes will require a substantial rewrite and we can discuss this in further issues.

Fixes https://github.com/Lightning-AI/lightning-bolts/issues/839

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does **only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes?
- [x] Did you write any **new necessary tests**? \[not needed for typos/docs\]
- [x] Did you verify new and **existing tests** pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-bolts/blob/master/CHANGELOG.md)?

## PR review

- [x] Is this pull request **ready for review**? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Atharva-Phatak** [comment]
@otaj If I made a mistake let me know. I don't know why other tests are not running. Locally its working at least CPU versions

**Comment by Atharva-Phatak** [comment]
Not sure why azure steps are failing. CPU runs are working on my local system.

**Comment by Atharva-Phatak** [comment]
Finally CI/CD passing on azure after so much time 🥺

**Comment by Atharva-Phatak** [comment]
@otaj need someone approval to run other tests. Azure pipelines and tests are passing. Please enable other tests so that this can get approved :)

**Comment by krshrimali** [comment]
> @otaj need someone approval to run other tests. Azure pipelines and tests are passing. Please enable other tests so that this can get approved :)

Hey, @Atharva-Phatak - Done! :) Feel free to ping us again in case you need approval for the tests. Since it's a weekend, I thought I'll help Ota and you out with this small little approval. 🚀

**Comment by Atharva-Phatak** [comment]
@krshrimali Yo thank you so much :)

**Comment by Atharva-Phatak** [comment]
@krshrimali could you trigger other runs. I want to check if mypy is skipping some lines of check as they are unnecessary ?

**Comment by krshrimali** [comment]
> @krshrimali could you trigger other runs. I want to check if mypy is skipping some lines of check as they are unnecessary ?

Done! :))

**Comment by Atharva-Phatak** [comment]
@krshrimali could you trigger other runs. I want to check if mypy is skipping some lines of check as they are unnecessary ?

**Comment by Atharva-Phatak** [comment]
Thanks for triggering the runs.

**Comment by Atharva-Phatak** [comment]
I am closing this PR and adding all the changes to a new PR as I have to contact someone to trigger the runs.

**Pull request closed without merging**
